---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: clustertopology-validating-webhook
  labels:
{{- include "operator.clustertopology.validating.webhook.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ required ".Values.service.name is required" .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /webhooks/validate-clustertopology
        port: {{ required ".Values.config.server.webhooks.port" .Values.config.server.webhooks.port }}
    failurePolicy: Fail
    matchPolicy: Exact
    name: clustertopology.validating.webhooks.grove.io
    namespaceSelector: { }
    rules:
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - clustertopologies
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 10

