apiVersion: v1
kind: Service
metadata:
  name: {{ required ".Values.service.name is required" .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "operator.serviceaccount.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{- include "operator.deployment.matchLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ required ".Values.config.server.metrics.port" .Values.config.server.metrics.port }}
      targetPort: {{ required ".Values.config.server.metrics.port" .Values.config.server.metrics.port }}
    - name: webhooks
      protocol: TCP
      port: {{ required ".Values.config.server.webhooks.port" .Values.config.server.webhooks.port }}
      targetPort: {{ required ".Values.config.server.webhooks.port" .Values.config.server.webhooks.port }}